site_name: 戯術memo
site_author: zaki
copyright: Copyright 2021 zaki

# repo_name: zaki-lknr/docs   # default: GitHub
repo_url: https://github.com/zaki-lknr/docs

theme:
  name: material
  language: 'ja'
  features:
    - navigation.tabs
  palette:
    scheme: default
    primary: orange
    accent: pink

extra:
  search:
    language: 'jp'
    # 日本語検索設定

markdown_extensions:
    # コードハイライトの設定
    - codehilite:
        noclasses: true
        pygments_style: emacs
        linenums: false
    - pymdownx.tilde
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_div_format

extra_css:
  - https://unpkg.com/mermaid@8.0.0/dist/mermaid.css

extra_javascript:
  - https://unpkg.com/mermaid@8.0.0/dist/mermaid.min.js

# https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/
google_analytics:
  - UA-199279483-2
  - 'auto'
